#ifndef COLORS_H
#define COLORS_H

#define BACKGROUND_COLOR_1      0x000000
#define BACKGROUND_COLOR_2      0x0E0E0E
#define ROCK_COLOR              0xDEDEDE
#define GHOST_COLOR             0x95ADC7
#define GROW_PACK_COLOR         0xFF00F3
#define PORTAL_PACK_COLOR       0x03FCF0
#define ATTACK_PACK_COLOR       0xF51435
#define END_TEXT_COLOR          0xFFFFFF

#define UI_TEXT_COLOR           0xCFCFCF
#define FADED_UI_TEXT_COLOR     0x7F7F7F
#define RED_UI_TEXT_COLOR       0xFF0000
#define CHALLENGE_ICON_COLOR    0xABEB34
#define HEART_ICON_COLOR        0xFF001E
#define STAR_ICON_COLOR         0xFFCF21
#define HIGHSCORE_ICON_COLOR    0xFC7703
#define PAUSED_ICON_COLOR       0xE0B601
#define RESUMED_ICON_COLOR      0x4A4A4A
#define CLOCK_ICON_COLOR        0x3BB0C4

#define RAINBOW_PACK_COLOR_1    0xFC0320
#define RAINBOW_PACK_COLOR_2    0xFC9803
#define RAINBOW_PACK_COLOR_3    0xE8FC03

#define TITLE_TEXT_COLOR_1      0xF27E11
#define TITLE_TEXT_COLOR_2      0xFCAA38

#define OPTION_TEXT_COLOR       0xFFFFFF
#define SELECT_ARROW_COLOR      0xEBE42A
#define START_OPTION_COLOR      0xFF36D161
#define QUIT_OPTION_COLOR       HEART_ICON_COLOR

#endif // COLORS_H
